### ISSUE TITLE
Project Boilerplate

### ISSUE THREAD

**Issue by Safnaj** [sliit-foss/rsvp#1]
@nandunbandara Aiya, Can u initialise and structure the project ? Then we can continue further.

**Comment by nandunbandara** [comment]
@Shehanka @Safnaj sure malli. What is the tech stack? NodeJS API and Angular frontend within the same repo?

**Comment by nisalrenuja** [comment]
![Uploading WhatsApp Image 2020-12-13 at 6.23.03 PM.jpeg…]()

**Comment by nisalrenuja** [comment]
![RSVP](https://user-images.githubusercontent.com/42801983/102038729-02000a80-3dee-11eb-95d3-ed6629129217.jpeg)

**Comment by ebonynon** [comment]
> @Shehanka @Safnaj sure malli. What is the tech stack? NodeJS API and Angular frontend within the same repo?

sliit-foss/rsvp :: FroentEnd
sliit-foss/rsvp-api :: BackEnd
sliit-foss/rsvp-interface :: FOSSBoard

**Comment by Shehanka** [comment]
> > @Shehanka @Safnaj sure malli. What is the tech stack? NodeJS API and Angular frontend within the same repo?
> 
> 
> 
> sliit-foss/rsvp :: FroentEnd
> 
> sliit-foss/rsvp-api :: BackEnd
> 
> sliit-foss/rsvp-interface :: FOSSBoard
> 
> 

Why do we need a rsvp frontend?

**Comment by Shehanka** [comment]
@ebonynon our initial plan was to create a separate route in sliit foss web for rsvp

**Comment by Safnaj** [comment]
@Shehanka @ebonynon We can have a seperate module & component for the RSVP inside our FOSS Website. In future if its needed we can easily move it.

**Comment by nandunbandara** [comment]
@Shehanka @Safnaj so basically this repo should contain the API right?

**Comment by Shehanka** [comment]
> @Shehanka @Safnaj so basically this repo should contain the API right?

Yes

**Comment by nandunbandara** [comment]
@Safnaj @Shehanka all done bois! 🥳

**Comment by nandunbandara** [comment]
Some key things to remember. 

1. Use semantic comments 🚀 
2. Write documentation (jsdocs) 📝 
3. Write unit and integration tests for everything you write. 🧪

**Comment by nandunbandara** [comment]
For reference checkout my commit messages and the code I've added. 

[https://gist.github.com/joshbuchea/6f47e86d2510bce28f8e7f42ae84c716](https://gist.github.com/joshbuchea/6f47e86d2510bce28f8e7f42ae84c716)

**Comment by Shehanka** [comment]
> Some key things to remember.
> 
> 1. Use semantic comments 🚀
> 2. Write documentation (jsdocs) 📝
> 3. Write unit and integration tests for everything you write. 🧪

@ebonynon Please include these details in the README
I'll set up a GitHub Action for the CI checks
