### ISSUE TITLE
Define endpoints

### ISSUE THREAD

**Issue by ebonynon** [sliit-foss/rsvp#17]

**Comment by ebonynon** [comment]
# Attendees

GET	{{domain}}/user	-	Get list of attendees
GET	{{domain}}/user/:id	-	Get a attendee by id
POST	{{domain}}/user/:id	-	Create a attendee

# Auth

POST	{{domain}}/user/login	-	Admin login
POST	{{domain}}/user/signup	-	Create a admin account

# Event

GET	{{domain}}/event	-	Get list of events
GET	{{domain}}/event/:id	-	Get a event by id
POST	{{domain}}/event/:id	-	Create a event

# Mail

POST {{domain}}/mail	-	Send mail/mails to attendee/attendees

# Health

GET	{{domain}}/health	-	Get health of the service

**Comment by ebonynon** [comment]
@nandunbandara @Shehanka What's your opinion?

**Comment by Shehanka** [comment]
POST {{domain}}/user/:id - Create a attendee

why did you put id param in a POST request?

**Comment by ebonynon** [comment]
> POST {{domain}}/user/:id - Create a attendee
> 
> why did you put id param in a POST request?

Done
