### ISSUE TITLE
Health Endpoint Implementation

### ISSUE THREAD

**Issue by sithumonline** [sliit-foss/rsvp#25]
GET	{{domain}}/health	-	Get health of the service

**Comment by ebonynon** [comment]
Assign to @SahasR

**Comment by SahasR** [comment]
![Capture](https://user-images.githubusercontent.com/56167123/110987261-d791ff00-8394-11eb-9e19-0cea4a7ce3cf.JPG)

Anything else that you want?

**Comment by ebonynon** [comment]
> ![Capture](https://user-images.githubusercontent.com/56167123/110987261-d791ff00-8394-11eb-9e19-0cea4a7ce3cf.JPG)
> 
> Anything else that you want? 

`{"data":"rsvp up and running version: Development"}`

Get the version number using event veritable.

**Comment by SahasR** [comment]
Okay <3
