### ISSUE TITLE
MongoDB Atlas

### ISSUE THREAD

**Issue by Safnaj** [sliit-foss/rsvp#9]
If possible shall we have the Mongo Db in Atlas. We can use GitHub Student Developer Pack for free access.

@Shehanka if we can mange it with local Mongo, close this issue.

**Comment by ebonynon** [comment]
https://github.com/sliit-foss/rsvp/blob/4778b4e58cc20b06228c76552e0cc01918149325/src/config/index.js#L11

We can use Atlas or self-hosted db as our wish.

**Comment by nandunbandara** [comment]
@Safnaj lets stick to local instances for development purposes and move to an atlas instance once we are ready with the deployment.
